exclude: '^(\\.git/|.*cache.*/|.*migrations/|.*docker/)'

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        language_version: python3.11

-   repo: https://github.com/PyCQA/autoflake
    rev: 'v2.2.1'
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.1'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo:  https://github.com/PyCQA/pylint
    rev: 'v3.0.1'
    hooks:
    -   id: pylint
        args: [--rcfile=pyproject.toml]
