version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine3.17
    container_name: weblinker-postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data/
