"""create user and events tables

Revision ID: bacb5816bcf1
Revises: 
Create Date: 2023-11-12 11:46:55.751049

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bacb5816bcf1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create account schema, i create this code manually
    op.execute("CREATE SCHEMA IF NOT EXISTS accounts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        schema="accounts",
    )
    op.create_index(
        op.f("ix_accounts_users_id"), "users", ["id"], unique=False, schema="accounts"
    )
    op.create_index(
        op.f("ix_accounts_users_uuid"),
        "users",
        ["uuid"],
        unique=True,
        schema="accounts",
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_events_id"), "events", ["id"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_events_uuid"), "events", ["uuid"], unique=True, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_events_uuid"), table_name="events", schema="public")
    op.drop_index(op.f("ix_public_events_id"), table_name="events", schema="public")
    op.drop_table("events", schema="public")
    op.drop_index(op.f("ix_accounts_users_uuid"), table_name="users", schema="accounts")
    op.drop_index(op.f("ix_accounts_users_id"), table_name="users", schema="accounts")
    op.drop_table("users", schema="accounts")
    # ### end Alembic commands ###

    # Drop account schema, i create this code manually
    op.execute("DROP SCHEMA IF EXISTS accounts")
